server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: 123456
    key-store: keystore.p12
spring:
  thymeleaf:
    cache: false
custom:
  site:
    baseUrl: https://localhost